# This file was generated by GoReleaser. DO NOT EDIT.
cask "argus" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "37ebb87e57aab0a55ac0e9767447e0a1dbc19fada2e0df828a0b275bd3fffd78"
      url "https://github.com/Tzomily-Anvar/argus/releases/download/v#{version}/argus_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1539a5100a5d4b26b80fb13f321ccb2866692b716a1b13acc575292d278b90d5"
      url "https://github.com/Tzomily-Anvar/argus/releases/download/v#{version}/argus_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "833f97951ba5f081da837b32e74182c586d34379131fe78b7969202d6e3e2889"
      url "https://github.com/Tzomily-Anvar/argus/releases/download/v#{version}/argus_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d114240830a42cb1e9cdd0ad9ed37232700e52fd3c63f865f53eb7adad8f8cfa"
      url "https://github.com/Tzomily-Anvar/argus/releases/download/v#{version}/argus_#{version}_linux_amd64.tar.gz"
    end
  end

  name "argus"
  desc "A read-only dashboard for what a GitHub organisation is doing"
  homepage "https://github.com/Tzomily-Anvar/argus"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "argus"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/argus"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Argus keeps its configuration in your home directory and holds no
    credential of its own beyond the session you create by signing in.

        argus init      write a starter config, then set your org in it
        argus login     sign in to GitHub - no token, no private key
        argus doctor    check it over
        argus           run it

    To keep it sweeping in the background, so the dashboard is already
    up to date whenever you open it:

        argus service install
  EOS
end
