# This file was generated by GoReleaser. DO NOT EDIT.
cask "argus" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "057157554078cd204bdc03e181315b9a965fc10ea45d1fce3240b5fcfd439eb3"
      url "https://github.com/Tzomily-Anvar/argus/releases/download/v#{version}/argus_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1169a6237d8cae1ac0bf4aeea841b3da9096b11a21aa6db53e6f3b0a72ffbfc0"
      url "https://github.com/Tzomily-Anvar/argus/releases/download/v#{version}/argus_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "05caa8f56d3a4b062dc4ca09330487e4f6dbfde233c099ae12b36477afbaca09"
      url "https://github.com/Tzomily-Anvar/argus/releases/download/v#{version}/argus_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d1788961d546432324c3cf3503f64eef4756574d4c3e5776be7a4b4f5e847d51"
      url "https://github.com/Tzomily-Anvar/argus/releases/download/v#{version}/argus_#{version}_linux_amd64.tar.gz"
    end
  end

  name "argus"
  desc "A read-only dashboard for what a GitHub organisation is doing"
  homepage "https://github.com/Tzomily-Anvar/argus"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "argus"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/argus"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Argus keeps its configuration in your home directory and holds no
    credential of its own beyond the session you create by signing in.

        argus init      write a starter config, then set your org in it
        argus login     sign in to GitHub - no token, no private key
        argus doctor    check it over
        argus           run it

    To keep it sweeping in the background, so the dashboard is already
    up to date whenever you open it:

        argus service install
  EOS
end
