# This file was generated by GoReleaser. DO NOT EDIT.
cask "argus" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "f1d7a459c3206fc4670f4835a18f60c1d92428f7376dba32de6b33a8d9f532db"
      url "https://github.com/Tzomily-Anvar/argus/releases/download/v#{version}/argus_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6bc971b55bf103cb288b32ecb8cafa5caac44d3e6446f725ba958ec408ff1a39"
      url "https://github.com/Tzomily-Anvar/argus/releases/download/v#{version}/argus_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d3f9fc1b4e9f9a58247218b398079d031073e84a6ea3624596906a7fcb8dfca7"
      url "https://github.com/Tzomily-Anvar/argus/releases/download/v#{version}/argus_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "44c54f72fc7280d3f83f8c8e74dfa50c26216f54fad48d66069163df2dd3a41d"
      url "https://github.com/Tzomily-Anvar/argus/releases/download/v#{version}/argus_#{version}_linux_amd64.tar.gz"
    end
  end

  name "argus"
  desc "A read-only dashboard for what a GitHub organisation is doing"
  homepage "https://github.com/Tzomily-Anvar/argus"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "argus"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/argus"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Argus keeps its configuration in your home directory and holds no
    credential of its own beyond the session you create by signing in.

        argus init      write a starter config, then set your org in it
        argus login     sign in to GitHub - no token, no private key
        argus doctor    check it over
        argus           run it

    To keep it sweeping in the background, so the dashboard is already
    up to date whenever you open it:

        argus service install
  EOS
end
